function xdot = modelCD_simplified(t, x, u, theta)

% theta = [nstages, k0, K0, Q, E, rhoCp, negDeltaH, rhoB, epz, MT, k0d, Ed, P, L, r, DeB, sensorPosition];
%             1        2   3   4  5  6      7          8     9    10  11   12  13 14 15 16   17
%  nstages   = theta{01};
         
%    xdot = [ ...       
% %% 0. xB
%     
% %  zeros(nstages-1,1); % XB 2-nstages
%     alpha(1) .* (x(0*nstages+(2:nstages-1)+1)-2 .* x(0*nstages+(2:nstages-1)) + x(0*nstages+(2:nstages-1)-1)) ./ deltaZ^2 ...
%     - u(6) .* (x(0*nstages+(2:nstages-1)) - x(0*nstages+(2:nstages-1) - 1)) ./ deltaZ  ...
%     - alpha(2) .* exp( -alpha(3) ./ x(4*nstages + (2:nstages-1))) .* ...
%       x(0*nstages + (2:nstages-1)) .* ...
%       x(1*nstages + (2:nstages-1)) .* ...
%       x(5*nstages + (2:nstages-1));
%            
% %% 1. xH
%     
% %  zeros(nstages-1,1); % XH 2-nstages-1
%     alpha(1) .* (x(0*nstages+(2:nstages-1)+1)-2 .* x(0*nstages+(2:nstages-1)) + x(0*nstages+(2:nstages-1)-1)) ./ deltaZ^2 ...
%     - u(6) .* (x(0*nstages+(2:nstages-1)) - x(0*nstages+(2:nstages-1) - 1)) ./ deltaZ  ...
%     - alpha(2) .* exp( -alpha(3) ./ x(4*nstages + (2:nstages-1))) .* ...
%       x(0*nstages + (2:nstages-1)) .* 
%       x(1*nstages + (2:nstages-1)) .* ...
%       x(5*nstages + (2:nstages-1));        
%    
% %% 2. xP
%     
% %  zeros(nstages-1,1); % XP 2-nstages
%     alpha(1) .* (x(0*nstages+(2:nstages-1)+1)-2 .* x(0*nstages+(2:nstages-1)) + x(0*nstages+(2:nstages-1)-1)) ./ deltaZ^2 ...
%     - u(6) .* (x(0*nstages+(2:nstages-1)) - x(0*nstages+(2:nstages-1) - 1)) ./ deltaZ  ...
%     + alpha(2) .* exp( -alpha(3) ./ x(4*nstages + (2:nstages-1))) .* ...
%       x(0*nstages + (2:nstages-1)) .* ...
%       x(1*nstages + (2:nstages-1)) .* ...
%       x(5*nstages + (2:nstages-1));
%          
% %% 3. xT
%     
% %  zeros(nstages-1,1); % XT 2-nstages-1
%     alpha(4) .* (x(3*nstages+(2:nstages-1)+1)-2 .* x(3*nstages+(2:nstages-1)) + x(3*nstages+(2:nstages-1)-1)) ./ deltaZ^2 ...
%     - u(6) .* (x(3*nstages + (2:nstages-1)) - x(3*nstages + (2:nstages-1) - 1)) ./ deltaZ  ...
%     - \alpha(5) .* exp(- alpha(6) ./ x(4*nstages + (2:nstages-1))) .* ...
%       x(3*nstages + (2:nstages-1)) .* 
%       x(5*nstages + (2:nstages-1));  
% %     
% % %% 4. T
% %     
% % %  zeros(nstages-1,1); % T 2-nstages                                        
% %     -u(6) .* alpha(9) .* (x(4*nstages+(2:nstages-1)) - x(4*nstages+(2:nstages-1)-1)) ./ deltaZ  ...
% %     + negDeltaH ./ rhoCp .* (P / R / x(4*nstages + (2:nstages-1))) .* ...
% %     rhoB ./ P ./epz .* R .* x(4*nstages + (2:nstages-1)) .* ...
% %     P .* x(0*nstages + (2:nstages-1)) .* ...
% %     P .* x(1*nstages + (2:nstages-1)) .* ...
% %     k0 .* K0 .* ...
% %     exp((-Q -E) ./ R ./ x(4*nstages + (2:nstages-1))) ./ ...
% %     (1 + K0 .* exp(-Q ./ R ./ x(4*nstages + (2:nstages-1))) .* P .* x(0*nstages + (2:nstages-1))) .* ...
% %     x(5*nstages + (2:nstages-1));
% %     
% % %% 5. Theta
% %
% % %  zeros(nstages-1,1); % Theta 2-nstages
% %    - alpha(7) .* exp(- alpha(6) ./ x(4*nstages+(2:nstages)));
%    ]; 
% %     
 end