function xdot = modelCD(t, x, u, theta)
    
    %% Unpack parameters
%   theta = [nstages, k0, K0, Q, E, rhoCp, negDeltaH, rhoB, epz, MT, k0d, Ed, P, L, r, DeB, sensorPosition];
%            1        2   3   4  5  6      7          8     9    10  11   12  13 14 15 16   17

    nstages   = theta{01};
    
    k0        = theta{02};     % (kmol/(kg*s*Pa))  Pre exponential factor for hydrogenation
    K0        = theta{03};     % (1/Pa)            Adsorption constant for benzene
    Q         = theta{04};     % (J/kmol)          Benzene adsorption activation energy
    E         = theta{05};     % (J/kmol)          Activation energy of hydrogenation
    rhoCp     = theta{06};     % (J/(m^3*C))       Effective heat capacity, of reactor
    negDeltaH = theta{07};     % (J/kmol)          Heat of reaction
    rhoB      = theta{08};     % (kg/m^3)          Benzene density
    epz       = theta{09};     %                   Void fraction
    MT        = theta{10};     % (kg/kmol)         Poison adsorption capacity of catalyst
    k0d       = theta{11};     % ((Pa*s)^-1)       Pre exponential factor for poisoning
    Ed        = theta{12};     % (J/kmol)          Activation energy of poisoning
    P         = theta{13};     % (Pa)              Pressure
    L         = theta{14};     % (m)               Reactor's length
    DeB       = theta{16};
    
    R         = 8.314*10^3;    % J/kmol/C
    deltaZ    = L/nstages;     % (m)
    
    %%  State variables (Equations must be checked)
    
    % U1 - XB0
    % U2 - XH0
    % U3 - XP0
    % U4 - XT0
    % U5 - T0
    % U6 - U
    
    % XB -  0 * nstages + 1 | 0 * nstages + 2 --> 1 * nstages
    % XH -  1 * nstages + 1 | 1 * nstages + 2 --> 2 * nstages
    % XP -  2 * nstages + 1 | 2 * nstages + 2 --> 3 * nstages
    % XT -  3 * nstages + 1 | 3 * nstages + 2 --> 4 * nstages
    % T  -  4 * nstages + 1 | 4 * nstages + 2 --> 5 * nstages
    % Th -  5 * nstages + 1 | 4 * nstages + 2 --> 6 * nstages
        
    xdot = [ ...       
%% 0. xB
%  0; % xB 1
    DeB * (x(0*nstages+2) - 2*x(0*nstages+1) + u(1)) / deltaZ^2 ...
    - u(6)  * (x(0*nstages+1) - u(1)) / deltaZ ...
    - rhoB / P /epz * R * x(4*nstages + 1) * ...
    P * x(0*nstages + 1) * ...
    P * x(1*nstages + 1) * ...
    k0 * K0 * ...
    exp((-Q-E) / R / x(4*nstages + 1)) / ...
    (1 + K0 * exp(-Q / R / x(4*nstages + 1)) * P * x(0*nstages + 1)) * ...
    x(5*nstages + 1); 
    
%  zeros(nstages-1,1); % XB 2-nstages
    DeB .* (x(0*nstages+(2:nstages-1)+1)-2 .* x(0*nstages+(2:nstages-1)) + x(0*nstages+(2:nstages-1)-1)) ./ deltaZ^2 ...
    - u(6) .* (x(0*nstages+(2:nstages-1)) - x(0*nstages+(2:nstages-1) - 1)) ./ deltaZ  ...
    - rhoB ./ P ./epz .* R .* x(4*nstages + (2:nstages-1)) .* ...
    P .* x(0*nstages + (2:nstages-1)) .* ...
    P .* x(1*nstages + (2:nstages-1)) .* ...
    k0 .* K0 .* ...
    exp((-Q -E) ./ R ./ x(4*nstages + (2:nstages-1))) ./ ...
    (1 + K0 .* exp(-Q ./ R ./ x(4*nstages + (2:nstages-1))) .* P .* x(0*nstages + (2:nstages-1))) .* ...
    x(5*nstages + (2:nstages-1));
    
%  zeros(nstages-1,1); % XB nstages
    DeB * (x(1*nstages) - 2*x(1*nstages-1) + x(1*nstages-2)) / deltaZ^2 ...
    - u(6)  * (x(1*nstages) - x(1*nstages-1)) / deltaZ /2 ...
    - rhoB / P /epz * R * x(5*nstages) * ...
    P * x(1*nstages) * ...
    P * x(2*nstages) * ...
    k0 * K0 * ...
    exp((-Q-E) / R / x(5*nstages)) / ...
    (1 + K0 * exp(-Q / R / x(5*nstages)) * P * x(1*nstages)) * ...
    x(6*nstages); 
           
%% 1. xH
%  0; % xH 1
    DeB * (x(1*nstages+2)-2*x(1*nstages+1) + u(2)) / deltaZ^2 ...
    - u(6)  * (x(1*nstages+1) - u(2)) / deltaZ ...
    - rhoB / P /epz * R * x(4*nstages + 1) * ...
    P * x(0*nstages + 1) * ...
    P * x(1*nstages + 1) * ...
    k0 * K0 * ...
    exp((-Q-E) / R / x(4*nstages + 1)) / ...
    (1 + K0 * exp(-Q / R / x(4*nstages + 1)) * P * x(0*nstages + 1)) * ...
    x(5*nstages + 1); 
    
%  zeros(nstages-1,1); % XH 2-nstages-1
    DeB .* (x(1*nstages+(2:nstages-1)+1)-2 .* x(1*nstages+(2:nstages-1)) + x(1*nstages+(2:nstages-1)-1)) ./ deltaZ^2 ...
    - u(6) .* (x(1*nstages+(2:nstages-1)) - x(1*nstages+(2:nstages-1) - 1)) ./ deltaZ  ...
    - rhoB ./ P ./epz .* R .* x(4*nstages + (2:nstages-1)) .* ...
    P .* x(0*nstages + (2:nstages-1)) .* ...
    P .* x(1*nstages + (2:nstages-1)) .* ...
    k0 .* K0 .* ...
    exp((-Q -E) ./ R ./ x(4*nstages + (2:nstages-1))) ./ ...
    (1 + K0 .* exp(-Q ./ R ./ x(4*nstages + (2:nstages-1))) .* P .* x(0*nstages + (2:nstages-1))) .* ...
    x(5*nstages + (2:nstages-1));
    
%  zeros(nstages-1,1); % XH nstages
    DeB * (x(2*nstages) - 2*x(2*nstages-1) + x(2*nstages-2)) / deltaZ^2 ...
    - u(6)  * (x(2*nstages) - x(2*nstages-1)) / deltaZ ...
    - rhoB / P /epz * R * x(5*nstages) * ...
    P * x(1*nstages) * ...
    P * x(2*nstages) * ...
    k0 * K0 * ...
    exp((-Q-E) / R / x(5*nstages)) / ...
    (1 + K0 * exp(-Q / R / x(5*nstages)) * P * x(1*nstages)) * ...
    x(6*nstages);             
   
%% 2. xP
%  0; % xP 1 
    DeB * (x(2*nstages+2)-2 * x(2*nstages+1) + u(3)) / deltaZ^2 ...
    - u(6)  * (x(2*nstages+1) - u(3)) / deltaZ ...
    + rhoB / P /epz * R * x(4*nstages + 1) * ...
    P * x(0*nstages + 1) * ...
    P * x(1*nstages + 1) * ...
    k0 * K0 * ...
    exp((-Q-E) / R / x(4*nstages + 1)) / ...
    (1 + K0 * exp(-Q / R / x(4*nstages + 1)) * P * x(0*nstages + 1)) * ...
    x(5*nstages + 1); 
    
%  zeros(nstages-1,1); % XP 2-nstages
   DeB .* (x(2*nstages+(2:nstages-1)+1)-2 .* x(2*nstages+(2:nstages-1)) + x(2*nstages+(2:nstages-1)-1)) ./ deltaZ^2 ...
    - u(6) .* (x(2*nstages+(2:nstages-1)) - x(2*nstages+(2:nstages-1) - 1)) ./ deltaZ  ...
    + rhoB ./ P ./epz .* R .* x(4*nstages + (2:nstages-1)) .* ...
    P .* x(0*nstages + (2:nstages-1)) .* ...
    P .* x(1*nstages + (2:nstages-1)) .* ...
    k0 .* K0 .* ...
    exp((-Q -E) ./ R ./ x(4*nstages + (2:nstages-1))) ./ ...
    (1 + K0 .* exp(-Q ./ R ./ x(4*nstages + (2:nstages-1))) .* P .* x(0*nstages + (2:nstages-1))) .* ...
    x(5*nstages + (2:nstages-1));
    
%  zeros(nstages-1,1); % XP nstages    
     DeB * (x(3*nstages) - 2*x(3*nstages-1) + x(3*nstages-2))/(deltaZ ^2) ...
    - u(6)  * (x(3*nstages) - x(3*nstages-1)) / deltaZ ...
    + rhoB / P /epz * R * x(5*nstages) * ...
    P * x(1*nstages) * ...
    P * x(2*nstages) * ...
    k0 * K0 * ...
    exp((-Q-E) / R / x(5*nstages)) / ...
    (1 + K0 * exp(-Q / R / x(5*nstages)) * P * x(1*nstages)) * ...
    x(6*nstages); 
         
%% 3. xT
%   0; % xT 1
    DeB * (x(3*nstages+2)-2 * x(3*nstages+1) + u(4)) / deltaZ^2 ...
    - u(6)  * (x(3*nstages + 1) - u(4)) / deltaZ ...
    + rhoB * R / epz / P * ...
    x(4*nstages + 1) * ...
    MT * ...
    P * x(3*nstages + 1) * ...
    -k0d * ...
    exp(-Ed / R / x(4*nstages + 1)) * ...
    x(5*nstages + 1)* x(5*nstages + 1);
    
%  zeros(nstages-1,1); % XT 2-nstages-1
    DeB .* (x(3*nstages+(2:nstages-1)+1)-2 .* x(3*nstages+(2:nstages-1)) + x(3*nstages+(2:nstages-1)-1)) ./ deltaZ^2 ...
    - u(6) .* (x(3*nstages + (2:nstages-1)) - x(3*nstages + (2:nstages-1) - 1)) ./ deltaZ  ...
    + rhoB .* R ./ epz ./ P .* ...
    x(4*nstages + (2:nstages-1)) .* ...
    MT .* ...
    P .* x(3*nstages + (2:nstages-1)) .* ...
    -k0d .* ...
    exp(-Ed ./ R ./ x(4*nstages + (2:nstages-1))) .* ...
    x(5*nstages + (2:nstages-1)) .*x(5*nstages + (2:nstages-1));  
    
%  zeros(nstages-1,1); % XT nstages    
    DeB * (x(3*nstages+2)-2 * x(3*nstages+1) + u(4)) / deltaZ^2 ...
    - u(6)  * (x(4*nstages) - x(4*nstages -1)) / deltaZ  ...
    + rhoB * R / epz / P * ...
    x(5*nstages) * ...
    MT * ...
    P * x(4*nstages) * ...
    -k0d * ...
    exp(-Ed / R / x(5*nstages)) * ...
    x(6*nstages)* x(6*nstages);
    
%% 4. T
%  0; % T 1   
    -u(6) * (P / R / x(4*nstages + 1)) / rhoCp * ...
    (2.902 * x(1* nstages + 1) + 9.686 * x(0*nstages + 1) ) * 10^4 *...
    (x(4*nstages+1) - u(5)) / deltaZ ...
    + negDeltaH / rhoCp * (P / R / x(4*nstages + 1)) * ...
    rhoB / P /epz * R * x(4*nstages + 1) * ...
    P * x(0*nstages + 1) * ...
    P * x(1*nstages + 1) * ...
    k0 * K0 * ...
    exp((-Q-E) / R / x(4*nstages + 1)) / ...
    (1 + K0 * exp(-Q / R / x(4*nstages + 1)) * P * x(0*nstages + 1)) * ...
    x(5*nstages + 1);
    
%  zeros(nstages-1,1); % T 2-nstages                                        
    -u(6) .* (P ./ R ./ x(4*nstages + (2:nstages-1))) ./ rhoCp .* ...
    (2.902 .* x(1* nstages + (2:nstages-1)) + 9.686 .* x(0*nstages + (2:nstages-1)) ) .* 10^4 .*...
    (x(4*nstages+(2:nstages-1)) - x(4*nstages+(2:nstages-1)-1)) ./ deltaZ   ...
    + negDeltaH ./ rhoCp .* (P / R / x(4*nstages + (2:nstages-1))) .* ...
    rhoB ./ P ./epz .* R .* x(4*nstages + (2:nstages-1)) .* ...
    P .* x(0*nstages + (2:nstages-1)) .* ...
    P .* x(1*nstages + (2:nstages-1)) .* ...
    k0 .* K0 .* ...
    exp((-Q -E) ./ R ./ x(4*nstages + (2:nstages-1))) ./ ...
    (1 + K0 .* exp(-Q ./ R ./ x(4*nstages + (2:nstages-1))) .* P .* x(0*nstages + (2:nstages-1))) .* ...
    x(5*nstages + (2:nstages-1));
    
%  zeros(nstages-1,1); % T nstages     
     -u(6) * (P / R / x(5*nstages )) / rhoCp * ...
    (2.902 * x(2* nstages) + 9.686 * x(1*nstages) ) * 10^4 *...
    (x(5*nstages) - x(5*nstages-1)) / deltaZ ...
    + negDeltaH / rhoCp * (P / R / x(5*nstages )) * ...
    rhoB / P /epz * R * x(5*nstages) * ...
    P * x(1*nstages) * ...
    P * x(2*nstages) * ...
    k0 * K0 * ...
    exp((-Q-E) / R / x(5*nstages)) / ...
    (1 + K0 * exp(-Q / R / x(5*nstages)) * P * x(1*nstages)) * ...
    x(6*nstages);
    
%% 5. Theta
%  0; % Theta 1 
  - k0d  * P  * x(3*nstages+1) * x(5*nstages+1) * exp(-Ed  / R  / x(4*nstages+1));                                
%  zeros(nstages-1,1); % Theta 2-nstages
   - k0d .* P .* x(3*nstages+(2:nstages)) .* x(5*nstages+(2:nstages)) .* exp(-Ed ./ R ./ x(4*nstages+(2:nstages)));
   ]; 
    
end



