function xdot = modelCD(t, x, u, theta)
    
    %% Unpack parameters
    
%   theta = [nstages, k0, K0, Q, E, rhoCp, negDeltaH, rhoB, epz, MT, k0d, Ed, P, L, r];
%            1        2   3   4  5  6      7          8     9    10  11   12  13 14 15

    nstages   = theta(01);
    
    k0        = theta(02);     % (kmol/(kg*s*Pa))  Pre exponential factor for hydrogenation
    K0        = theta(03);     % (1/Pa)            Adsorption constant for benzene
    Q         = theta(04);     % (J/kmol)          Benzene adsorption activation energy
    E         = theta(05);     % (J/kmol)          Activation energy of hydrogenation
    rhoCp     = theta(06);     % (J/(m^3*C))       Effective heat capacity, of reactor
    negDeltaH = theta(07);     % (J/kmol)          Heat of reaction
    rhoB      = theta(08);     % (kg/m^3)          Benzene density
    epz       = theta(09);     %                   Void fraction
    MT        = theta(10);     % (kg/kmol)         Poison adsorption capacity of catalyst
    k0d       = theta(11);     % ((Pa*s)^-1)       Pre exponential factor for poisoning
    Ed        = theta(12);     % (J/kmol)          Activation energy of poisoning
    P         = theta(13);     % (Pa)              Pressure
    L         = theta(14);     % (m)               Reactor's length
    
    R         = 8.314*10^3;    % J/kmol/C
    deltaZ    = L/nstages;     % (m)
    
    %%  State variables (Equations must be checked)
    
    % U1 - XB0
    % U2 - XH0
    % U3 - XP0
    % U4 - XT0
    % U5 - T0
    % U6 - U
    
    % XB -  0 * nstages + 1 | 0 * nstages + 2 --> 1 * nstages
    % XH -  1 * nstages + 1 | 1 * nstages + 2 --> 2 * nstages
    % XP -  2 * nstages + 1 | 2 * nstages + 2 --> 3 * nstages
    % XT -  3 * nstages + 1 | 3 * nstages + 2 --> 4 * nstages
    % T  -  4 * nstages + 1 | 4 * nstages + 2 --> 5 * nstages
    % Th -  5 * nstages + 1 | 4 * nstages + 2 --> 6 * nstages
        
    xdot = [ ...       
%% 0. xB
%  0; % xB1 
    - u(6)  * (x(0*nstages+1) - u(1)) / deltaZ ...
    - rhoB / P /epz * R * x(4*nstages + 1) * ...
    P * x(0*nstages + 1) * ...
    P * x(1*nstages + 1) * ...
    k0 * K0 * ...
    exp((-Q-E) / R / x(4*nstages + 1)) / ...
    (1 + K0 * exp(-Q / R / x(4*nstages + 1)) * P * x(0*nstages + 1)) * ...
    x(5*nstages + 1); 
%  zeros(nstages-1,1); % XB2-nstages
    - u(6) .* (x(0*nstages+(2:nstages)) - x(0*nstages+(2:nstages) - 1)) ./ deltaZ  ...
    - rhoB ./ P ./epz .* R .* x(4*nstages + (2:nstages)) .* ...
    P .* x(0*nstages + (2:nstages)) .* ...
    P .* x(1*nstages + (2:nstages)) .* ...
    k0 .* K0 .* ...
    exp((-Q -E) ./ R ./ x(4*nstages + (2:nstages))) ./ ...
    (1 + K0 .* exp(-Q ./ R ./ x(4*nstages + (2:nstages))) .* P .* x(0*nstages + (2:nstages))) .* ...
    x(5*nstages + (2:nstages)); 
           
%% 1. xH
%  0; % xH1 
    - u(6)  * (x(1*nstages+1) - u(2)) / deltaZ ...
    - rhoB / (P / R / x(4*nstages + 1)) /epz * ...
    P * x(0*nstages + 1) * ...
    P * x(1*nstages + 1) * ...
    k0 * K0 * ...
    exp((-Q-E) / R / x(4*nstages + 1)) / ...
    (1 + K0 * exp(-Q / R / x(4*nstages + 1)) * P * x(0*nstages + 1)) * ...
    x(5*nstages + 1);
%  zeros(nstages-1,1); % XH2-nstages
    - u(6) .* (x(1*nstages+(2:nstages)) - x(1*nstages+(2:nstages) - 1)) ./ deltaZ  ...
    - rhoB ./ (P ./ R ./ x(4*nstages + (2:nstages))) ./epz .* ...
    P .* x(0*nstages + (2:nstages)) .* ...
    P .* x(1*nstages + (2:nstages)) .* ...
    k0 .* K0 .* ...
    exp((-Q-E) ./ R ./ x(4*nstages + (2:nstages))) ./ ...
    (1 + K0 .* exp(-Q ./ R ./ x(4*nstages + (2:nstages))) .* P .* x(0*nstages + (2:nstages))) .* ...
    x(5*nstages + (2:nstages)); 
   
%% 2. xP
%  0; % xP1 
    - u(6)  * (x(2*nstages+1) - u(3)) / deltaZ ...
    + rhoB / (P / R / x(4*nstages + 1)) /epz * ...
    P * x(0*nstages + 1) * ...
    P * x(1*nstages + 1) * ...
    k0 * K0 * ...
    exp((-Q-E) / R / x(4*nstages + 1)) / ...
    (1 + K0 * exp(-Q / R / x(4*nstages + 1)) * P * x(0*nstages + 1)) * ...
    x(5*nstages + 1);
%  zeros(nstages-1,1); % XP2-nstages
    - u(6) .* (x(2*nstages+(2:nstages)) - x(2*nstages+(2:nstages) - 1)) ./ deltaZ  ...
    + rhoB ./ (P ./ R ./ x(4*nstages + (2:nstages))) ./epz .* ...
    P .* x(0*nstages + (2:nstages)) .* ...
    P .* x(1*nstages + (2:nstages)) .* ...
    k0 .* K0 .* ...
    exp((-Q -E) ./ R ./ x(4*nstages + (2:nstages))) ./ ...
    (1 + K0 .* exp(-Q ./ R ./ x(4*nstages + (2:nstages))) .* P .* x(0*nstages + (2:nstages))) .* ...
    x(5*nstages + (2:nstages));
         
%% 3. xT
%   0; % xT1 
    - u(6)  * (x(3*nstages + 1) - u(4)) / deltaZ ...
    - rhoB * R / epz / P / ...
    x(4*nstages + 1) * ...
    MT * ...
    P * x(3*nstages + 1) * ...
    -k0d * ...
    exp(-Ed / R / x(4*nstages + 1)) * ...
    x(5*nstages + 1);
%  zeros(nstages-1,1); % XT2-nstages
    - u(6) .* (x(3*nstages + (2:nstages)) - x(3*nstages + (2:nstages) - 1)) ./ deltaZ ...
    - rhoB .* R ./ epz ./ P ./ ...
    x(4*nstages + (2:nstages)) .* ...
    MT .* ...
    P .* x(3*nstages + (2:nstages)) .* ...
    -k0d .* ...
    exp(-Ed ./ R ./ x(4*nstages + (2:nstages))) .* ...
    x(5*nstages + (2:nstages));                                       
                                   
%% 4. T
%  0; % T1   
    -u(6) * (x(4*nstages+1) - u(5)) / deltaZ * ...
    (P / R / x(4*nstages + 1)) / rhoCp * ...
    (2.902 * x(1* nstages + 1) + 96.86 * x(0*nstages + 1) ) * 10^4 ...
    + negDeltaH / rhoCp * (P / R / x(4*nstages + 1)) * ...
    (2.106 * x(1* nstages + 1) + 78.12 * x(0*nstages + 1)) * ...
    epz * k0 * K0 * P * P * x(1*nstages+1)*...
    exp((-Q-E) / R / x(4*nstages + 1)) / ...
    (1 + K0 * exp(-Q / R / x(4*nstages + 1)) * P * x(0*nstages + 1)) * ...
    x(5*nstages + 1);
%  zeros(nstages-1,1); % T2-nstages                                        
    -u(6) .*  (x(4*nstages + (2:nstages)) - x(4*nstages+(2:nstages) - 1)) ./ deltaZ .* ...
    (P ./ R ./ x(4*nstages + (2:nstages))) ./ rhoCp .* ...
    (2.902 .* x(1* nstages + (2:nstages)) + 96.86 .* x(0*nstages + (2:nstages)) ) .* 10^4 ...
    + negDeltaH ./ rhoCp .* (P / R / x(4*nstages + (2:nstages))) .* ...
    (2.106 * x(1* nstages + (2:nstages)) + 78.12 .* x(0*nstages + (2:nstages))) .* ...
    epz .* k0 .* K0 .* P .* P .* x(1*nstages + (2:nstages)).*...
    exp((-Q-E) ./ R ./ x(4*nstages + (2:nstages))) ./ ...
    (1 + K0 * exp(-Q / R / x(4*nstages + (2:nstages))) .* P .* x(0*nstages + (2:nstages))) .* ...
    x(5*nstages + (2:nstages));
    
%% 5. Theta
%  0; % Theta 1 
  - k0d  * P  * x(3*nstages+1) * x(5*nstages+1) * exp(-Ed  / R  / x(4*nstages+1));                                
%  zeros(nstages-1,1); % Theta 2-nstages
   - k0d .* P .* x(3*nstages+(2:nstages)) .* x(5*nstages+(2:nstages)) .* exp(-Ed ./ R ./ x(4*nstages+(2:nstages)));
   ]; 
    
end



